openapi: "3.0.0"
info:
  version: 1.0.0
  title: Lamoda container API
  license:
    name: MIT
servers:
  - url: http://rsd23.com/lamoda/container-api/v1
paths:
  /containers:
    get:
      summary: List all containers
      operationId: listContainers
      tags:
        - containers
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of containers
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Containers"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a container
      operationId: createContainers
      tags:
        - containers
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /containers/{containerId}:
    get:
      summary: Info for a specific container
      operationId: showContainerById
      tags:
        - containers
      parameters:
        - name: containerId
          in: path
          required: true
          description: The id of the container to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Container"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Container:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
